planners:
  - name: 'global_planner'
    type: 'global_planner/GlobalPlanner'
planner_patience: 10.0
global_planner:
  allow_unknown: false
  default_tolerance: 0.0
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behaviour: false
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55