recovery_behaviors:
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'straf_recovery'
    type: 'straf_recovery/StrafRecovery' 
